config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: "posts#index"
  resources :users, only: [:show]
  resource :user_profile, only: [:edit, :update]
  
  resources :posts do
    resources :comments, shallow: true
  end
  
  resources :parks do
    member do
      post :join
      delete :leave
    end
  end
  
  get '/search', to: 'application#search'
end

app/models/park.rb
class Park < ApplicationRecord
  belongs_to :user
  has_many :park_users
  has_many :users, through: :park_users

  validates :name, presence: true
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_park, only: [:show, :edit, :update, :destroy, :join, :leave]
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def index
    @parks = Park.all
  end

  def new
    @park = current_user.created_parks.build
  end

  def create
    @park = current_user.created_parks.build(create_park_params)
    if @park.save
      redirect_to @park, notice: 'Park was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @park.update(update_park_params)
      redirect_to @park, notice: 'Park was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @park.park_users.destroy_all
    @park.destroy
    redirect_to root_url, notice: 'Park was successfully destroyed.'
  end

  def join
    if @park.users.include?(current_user)
      render json: { error: 'Already joined' }, status: :unprocessable_entity
    else
      @park.users << current_user
      render json: { success: 'Joined the park' }
    end
  end

  def leave
    if @park.users.include?(current_user)
      @park.users.delete(current_user)
      render json: { success: 'Left the park' }
    else
      render json: { error: 'Not a member' }, status: :unprocessable_entity
    end
  end

  private

  def set_park
    @park = Park.find(params[:id])
  end

  def ensure_correct_user
    return unless @park.user.nil? || @park.user != current_user

    redirect_to parks_path, alert: 'You are not authorized.'
  end

  def create_park_params
    params.require(:park).permit(:name, :info)
  end

  def update_park_params
    params.require(:park).permit(:info)
  end
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/views/parks/edit.html.erb
<%= form_with(model: @park, local: true) do |form| %>
  <div class="field">
    <%= form.label :info %>
    <%= form.text_area :info %>
  </div>
  <div class="actions">
    <%= form.submit "Update" %>
  </div>
<% end %>
<%= button_to 'Delete', @park, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn' %>

app/views/parks/index.html.erb
<div id="park-dropdown" class="park-dropdown">
  <% @parks.each do |park| %>
    <%= link_to park.name, park_path(park) %>
  <% end %>
</div>

app/views/parks/new.html.erb
<div class="new-park">
  <h1>新規パーク作成</h1>

  <%= form_with(model: @park, local: true) do |form| %>
    <div class="new-park-form">
      <%= form.label :name %>
      <%= form.text_field :name %>

      <%= form.label :info %>
      <%= form.text_area :info %>

      <div class="submit-button">
        <%= form.submit "作成" %>
      </div>
    </div>
  <% end %>

  <%= link_to "キャンセル", parks_path %>
</div>

app/views/parks/show.html.erb
<div class="park-header">
  <h1><%= @park.name %></h1>
  <button id="join-leave-btn" data-park-id="<%= @park.id %>" class="join-leave-btn">
    <% if @park.users.include?(current_user) %>
      Leave
    <% else %>
      Join
    <% end %>
  </button>
  <% if @park.user == current_user %>
    <%= link_to 'Edit', edit_park_path(@park), class: 'btn' %>
    <%= link_to 'Delete', park_path(@park), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn' %>
  <% end %>
</div>