config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: "posts#index"
  resources :users, only: [:show]
  resource :user_profile, only: [:edit, :update]
  
  resources :posts do
    resources :comments, shallow: true
  end
  
  resources :parks do
    member do
      post :join
      delete :leave
    end
  end
  
  get '/search', to: 'application#search'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: { message: 'を入力してください' }, uniqueness: { case_sensitive: true, message: 'は既に存在します' }
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'は半角英数字混合で入力してください' }

  has_one :user_profile, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy
  after_create :create_user_profile
  has_many :park_users
  has_many :parks, through: :park_users
  has_many :created_parks, class_name: 'Park', foreign_key: 'user_id'

  private

  def create_user_profile
    create_user_profile!(nickname: username)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<div class="profile">
  <%= image_tag user.user_profile.avatar.attached? ? user.user_profile.avatar : 'default_avatar.png', class: "avatar" %>
  <h2 class="nickname"><%= user.user_profile.nickname %></h2>
  <p class="username"><%= user.username %></p>

  <div class="buttons">
    <button class="follow-btn">Follow</button>
    <button class="talk-btn">Talk</button>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-detail">
  <div class="posts">
    <% @user.posts.order(created_at: :desc).each do |post| %>
      <div class="post">
        <div class="post-header">
          <%= link_to post.park.name, park_path(post.park), class: 'post-park' %>
          <span class="post-info">Posted by <%= link_to post.user.username, user_path(post.user), class: 'post-user' %> <%= time_ago_in_words(post.created_at) %> ago</span>
        </div>
        <h2><%= link_to post.title, post_path(post), class: "ustitle" %></h2>
        <p class="post-content"><%= markdown(truncate(post.content, length: 300)) %></p>

        <div class="comments">
          <h3>Comments</h3>
          <div class="comment-input">
            <!-- comment form goes here -->
          </div>
          <% post.comments.order(created_at: :desc).each do |comment| %>
            <div class="comment">
              <!-- comment display goes here -->
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <%= render 'users/profile', user: @user %>
</div>