config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: { registrations: 'registrations' }
  root to: "posts#index"
  resources :users, only: [:show]
  resource :user_profile, only: [:edit, :update]
  
  resources :posts do
    resources :comments, shallow: true
  end
  
  resources :parks do
    member do
      post :join
      delete :leave
    end
  end
  
  get '/search', to: 'application#search'
end

app/views/layouts/_ckeditor.html.erb
<div class="post-field" style="width: 800px;">
  <%= form.text_area field_name, id: "editor_#{SecureRandom.hex(10)}", class: 'post-textarea' %>
</div>

app/views/layouts/_content.html.erb
<main class="content">
  <% if user_signed_in? %>
    <%= link_to '新規投稿', new_post_path, class: 'content__new-post-button' %>
  <% end %>
  <div class="content__post-list">
    <% @posts.each do |post| %>
      <div class="post">
        <div class="posted-details">
          <div class="posted-header">
            <h3><%= link_to post.park.name, post.park %></h3>
            <p class="posted-info">
              Posted by <%= link_to post.user.username, post.user, class: "username" %> <%= time_ago_in_words(post.created_at) %> ago
            </p>
          </div>
          <div class="posted-title">
          <h2><%= link_to post.title, post_path(post) %></h2>
          </div>
          <div class="posted-textarea" id="post-<%= post.id %>">
            <div class="content-display">
              <%= markdown(post.content) %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</main>

app/views/layouts/_errors.html.erb
<% if flash[:error].present? %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:error] %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class='footer-content'>
  <div class='codenyan-contents'>
    <div class='codenyan-details'>
      <h2 class='footer-content-head'>CODENYANについて</h2>
      <ul class='footer-list'>
        <li>会社概要（運営会社)</li>
        <li>プライバシーポリシー</li>
        <li>CODENYAN利用規約</li>
      </ul>
    </div>
    <div class='codenyan-details'>
      <h2 class='footer-content-head'>CODENYANについて</h2>
      <ul class='footer-list'>
        <li>codenyanガイド</li>
        <li>codenyan利用ガイドライン</li>
        <li>お知らせ</li>
      </ul>
    </div>
  </div>
  <div class='footer-bottom'>
    <p>© CODENYAN</p>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="header">
    <div class="header__logo">
        <%= link_to root_path do %>
          <%= image_tag "logo.png", alt: "Codenyan logo" %>
        <% end %>
    </div>
    <div class="header__dropdown-container">
      <div class="select-label">Select Options</div>
      <div class="header__dropdown">
        <button class="dropdown-button"><%= @current_park_name || "Home" %></button>
        <div id="dropdown-content" class="dropdown-content" style="display: none;">
          <input type="text" id="search" placeholder="Filter">
          <%= link_to '新規投稿', new_post_path, class: 'dropdown-item' %>
          <%= link_to 'パーク作成', new_park_path, class: 'dropdown-item' %>
          <div class="dropdown-section-title">YOUR PARKS</div>
          <% if user_signed_in? %>
            <% current_user.parks.each do |park| %>
              <%= link_to park.name, park_path(park), class: 'dropdown-item' %>
            <% end %>
          <% end %>
          <div class="dropdown-section-title">OTHER</div>
          <% if user_signed_in? %>
            <%= link_to 'ユーザー設定', edit_user_registration_path, class: 'dropdown-item' %>
            <%= link_to 'プロフィール設定', edit_user_profile_path, class: 'dropdown-item' %>
          <% end %>
          <%= link_to 'Home', root_path, class: 'dropdown-item' %>
        </div>
      </div>
    </div>
    <div class="header__search">
        <%= form_with url: "/search", method: :get, html: { class: "search-form" } do |f| %>
            <%= f.text_field :q, placeholder: "Search..." %>
        <% end %>
        <div id="search-results" style="display: none;"></div>
    </div>
    <div class="header__icons">
        <a href="#"><img class="talk-icon" src="<%= asset_path 'talk-icon.png' %>" alt="Talk Icon"></a> <!-- talk functionality to be implemented -->
        <a href="#"><img class="notification-icon" src="<%= asset_path 'notification-icon.png' %>" alt="Notification Icon"></a> <!-- notification functionality to be implemented -->
    </div>
    <div class="header__profile">
      <% if user_signed_in? && current_user.user_profile %>
        <% if current_user.user_profile.avatar.attached? %>
          <%= image_tag current_user.user_profile.avatar, alt: "User avatar" %>
        <% else %>
          <%= image_tag 'default_avatar.png', alt: "Default avatar" %>
        <% end %>
        <span><%= current_user.username %></span>
      <% else %>
        <%= image_tag 'default_avatar.png', alt: "Guest avatar" %>
        <span>Guest</span>
      <% end %>
    </div>
    <div class="header__auth">
      <% if user_signed_in? %>
        <%= link_to '登録情報編集', edit_user_registration_path %>
        <%= link_to 'プロフィール', edit_user_profile_path, class: 'button' %>
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to '新規登録', new_user_registration_path %>
        <%= link_to 'ログイン', new_user_session_path %>
      <% end %>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codenyan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'avatar_preview' %>
    <%= javascript_pack_tag 'header_dropdown', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'search', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'join_leave' %>
    <%= javascript_pack_tag 'post_title_scroll' %>
    <%= javascript_pack_tag 'post_title_count', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'post_edit' %>
    <%= javascript_pack_tag 'comment_ajax' %>
    <%= javascript_pack_tag 'comment_edit' %>

  </head>

  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <div class="content">
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>